export interface ISO_Country {
  englishShortName: string,
	frenchShortName: string,
	alpha2Code: string,
}

export const ISO3166_Countries: ISO_Country[] = [
	{
		englishShortName: "Afghanistan",
		frenchShortName: "Afghanistan (l')",
		alpha2Code: "AF",
		// numeric: 4,
	},
	{
		englishShortName: "Albania",
		frenchShortName: "Albanie (l')",
		alpha2Code: "AL",
		// numeric: 8,
	},
	{
		englishShortName: "Algeria",
		frenchShortName: "Algérie (l')",
		alpha2Code: "DZ",
		// numeric: 12,
	},
	{
		englishShortName: "American Samoa",
		frenchShortName: "Samoa américaines (les)",
		alpha2Code: "AS",
		// numeric: 16,
	},
	{
		englishShortName: "Andorra",
		frenchShortName: "Andorre (l')",
		alpha2Code: "AD",
		// numeric: 20,
	},
	{
		englishShortName: "Angola",
		frenchShortName: "Angola (l')",
		alpha2Code: "AO",
		// numeric: 24,
	},
	{
		englishShortName: "Anguilla",
		frenchShortName: "Anguilla",
		alpha2Code: "AI",
		// numeric: 660,
	},
	{
		englishShortName: "Antarctica",
		frenchShortName: "Antarctique (l')",
		alpha2Code: "AQ",
		// numeric: 10,
	},
	{
		englishShortName: "Antigua and Barbuda",
		frenchShortName: "Antigua-et-Barbuda",
		alpha2Code: "AG",
		// numeric: 28,
	},
	{
		englishShortName: "Argentina",
		frenchShortName: "Argentine (l')",
		alpha2Code: "AR",
		// numeric: 32,
	},
	{
		englishShortName: "Armenia",
		frenchShortName: "Arménie (l')",
		alpha2Code: "AM",
		// numeric: 51,
	},
	{
		englishShortName: "Aruba",
		frenchShortName: "Aruba",
		alpha2Code: "AW",
		// numeric: 533,
	},
	{
		englishShortName: "Australia",
		frenchShortName: "Australie (l')",
		alpha2Code: "AU",
		// numeric: 36,
	},
	{
		englishShortName: "Austria",
		frenchShortName: "Autriche (l')",
		alpha2Code: "AT",
		// numeric: 40,
	},
	{
		englishShortName: "Azerbaijan",
		frenchShortName: "Azerbaïdjan (l')",
		alpha2Code: "AZ",
		// numeric: 31,
	},
	{
		englishShortName: "Bahamas (the)",
		frenchShortName: "Bahamas (les)",
		alpha2Code: "BS",
		// numeric: 44,
	},
	{
		englishShortName: "Bahrain",
		frenchShortName: "Bahreïn",
		alpha2Code: "BH",
		// numeric: 48,
	},
	{
		englishShortName: "Bangladesh",
		frenchShortName: "Bangladesh (le)",
		alpha2Code: "BD",
		// numeric: 50,
	},
	{
		englishShortName: "Barbados",
		frenchShortName: "Barbade (la)",
		alpha2Code: "BB",
		// numeric: 52,
	},
	{
		englishShortName: "Belarus",
		frenchShortName: "Bélarus (le)",
		alpha2Code: "BY",
		// numeric: 112,
	},
	{
		englishShortName: "Belgium",
		frenchShortName: "Belgique (la)",
		alpha2Code: "BE",
		// numeric: 56,
	},
	{
		englishShortName: "Belize",
		frenchShortName: "Belize (le)",
		alpha2Code: "BZ",
		// numeric: 84,
	},
	{
		englishShortName: "Benin",
		frenchShortName: "Bénin (le)",
		alpha2Code: "BJ",
		// numeric: 204,
	},
	{
		englishShortName: "Bermuda",
		frenchShortName: "Bermudes (les)",
		alpha2Code: "BM",
		// numeric: 60,
	},
	{
		englishShortName: "Bhutan",
		frenchShortName: "Bhoutan (le)",
		alpha2Code: "BT",
		// numeric: 64,
	},
	{
		englishShortName: "Bolivia (Plurinational State of)",
		frenchShortName: "Bolivie (État plurinational de)",
		alpha2Code: "BO",
		// numeric: 68,
	},
	{
		englishShortName: "Bonaire, Sint Eustatius and Saba",
		frenchShortName: "Bonaire, Saint-Eustache et Saba",
		alpha2Code: "BQ",
		// numeric: 535,
	},
	{
		englishShortName: "Bosnia and Herzegovina",
		frenchShortName: "Bosnie-Herzégovine (la)",
		alpha2Code: "BA",
		// numeric: 70,
	},
	{
		englishShortName: "Botswana",
		frenchShortName: "Botswana (le)",
		alpha2Code: "BW",
		// numeric: 72,
	},
	{
		englishShortName: "Bouvet Island",
		frenchShortName: "Bouvet (l'Île)",
		alpha2Code: "BV",
		// numeric: 74,
	},
	{
		englishShortName: "Brazil",
		frenchShortName: "Brésil (le)",
		alpha2Code: "BR",
		// numeric: 76,
	},
	{
		englishShortName: "British Indian Ocean Territory (the)",
		frenchShortName: "Indien (le Territoire britannique de l'océan)",
		alpha2Code: "IO",
		// numeric: 86,
	},
	{
		englishShortName: "Brunei Darussalam",
		frenchShortName: "Brunéi Darussalam (le)",
		alpha2Code: "BN",
		// numeric: 96,
	},
	{
		englishShortName: "Bulgaria",
		frenchShortName: "Bulgarie (la)",
		alpha2Code: "BG",
		// numeric: 100,
	},
	{
		englishShortName: "Burkina Faso",
		frenchShortName: "Burkina Faso (le)",
		alpha2Code: "BF",
		// numeric: 854,
	},
	{
		englishShortName: "Burundi",
		frenchShortName: "Burundi (le)",
		alpha2Code: "BI",
		// numeric: 108,
	},
	{
		englishShortName: "Cabo Verde",
		frenchShortName: "Cabo Verde",
		alpha2Code: "CV",
		// numeric: 132,
	},
	{
		englishShortName: "Cambodia",
		frenchShortName: "Cambodge (le)",
		alpha2Code: "KH",
		// numeric: 116,
	},
	{
		englishShortName: "Cameroon",
		frenchShortName: "Cameroun (le)",
		alpha2Code: "CM",
		// numeric: 120,
	},
	{
		englishShortName: "Canada",
		frenchShortName: "Canada (le)",
		alpha2Code: "CA",
		// numeric: 124,
	},
	{
		englishShortName: "Cayman Islands (the)",
		frenchShortName: "Caïmans (les Îles)",
		alpha2Code: "KY",
		// numeric: 136,
	},
	{
		englishShortName: "Central African Republic (the)",
		frenchShortName: "République centrafricaine (la)",
		alpha2Code: "CF",
		// numeric: 140,
	},
	{
		englishShortName: "Chad",
		frenchShortName: "Tchad (le)",
		alpha2Code: "TD",
		// numeric: 148,
	},
	{
		englishShortName: "Chile",
		frenchShortName: "Chili (le)",
		alpha2Code: "CL",
		// numeric: 152,
	},
	{
		englishShortName: "China",
		frenchShortName: "Chine (la)",
		alpha2Code: "CN",
		// numeric: 156,
	},
	{
		englishShortName: "Christmas Island",
		frenchShortName: "Christmas (l'Île)",
		alpha2Code: "CX",
		// numeric: 162,
	},
	{
		englishShortName: "Cocos (Keeling) Islands (the)",
		frenchShortName: "Cocos (les Îles)/ Keeling (les Îles)",
		alpha2Code: "CC",
		// numeric: 166,
	},
	{
		englishShortName: "Colombia",
		frenchShortName: "Colombie (la)",
		alpha2Code: "CO",
		// numeric: 170,
	},
	{
		englishShortName: "Comoros (the)",
		frenchShortName: "Comores (les)",
		alpha2Code: "KM",
		// numeric: 174,
	},
	{
		englishShortName: "Congo (the Democratic Republic of the)",
		frenchShortName: "Congo (la République démocratique du)",
		alpha2Code: "CD",
		// numeric: 180,
	},
	{
		englishShortName: "Congo (the)",
		frenchShortName: "Congo (le)",
		alpha2Code: "CG",
		// numeric: 178,
	},
	{
		englishShortName: "Cook Islands (the)",
		frenchShortName: "Cook (les Îles)",
		alpha2Code: "CK",
		// numeric: 184,
	},
	{
		englishShortName: "Costa Rica",
		frenchShortName: "Costa Rica (le)",
		alpha2Code: "CR",
		// numeric: 188,
	},
	{
		englishShortName: "Croatia",
		frenchShortName: "Croatie (la)",
		alpha2Code: "HR",
		// numeric: 191,
	},
	{
		englishShortName: "Cuba",
		frenchShortName: "Cuba",
		alpha2Code: "CU",
		// numeric: 192,
	},
	{
		englishShortName: "Curaçao",
		frenchShortName: "Curaçao",
		alpha2Code: "CW",
		// numeric: 531,
	},
	{
		englishShortName: "Cyprus",
		frenchShortName: "Chypre",
		alpha2Code: "CY",
		// numeric: 196,
	},
	{
		englishShortName: "Czechia",
		frenchShortName: "Tchéquie (la)",
		alpha2Code: "CZ",
		// numeric: 203,
	},
	{
		englishShortName: "Côte d'Ivoire",
		frenchShortName: "Côte d'Ivoire (la)",
		alpha2Code: "CI",
		// numeric: 384,
	},
	{
		englishShortName: "Denmark",
		frenchShortName: "Danemark (le)",
		alpha2Code: "DK",
		// numeric: 208,
	},
	{
		englishShortName: "Djibouti",
		frenchShortName: "Djibouti",
		alpha2Code: "DJ",
		// numeric: 262,
	},
	{
		englishShortName: "Dominica",
		frenchShortName: "Dominique (la)",
		alpha2Code: "DM",
		// numeric: 212,
	},
	{
		englishShortName: "Dominican Republic (the)",
		frenchShortName: "dominicaine (la République)",
		alpha2Code: "DO",
		// numeric: 214,
	},
	{
		englishShortName: "Ecuador",
		frenchShortName: "Équateur (l')",
		alpha2Code: "EC",
		// numeric: 218,
	},
	{
		englishShortName: "Egypt",
		frenchShortName: "Égypte (l')",
		alpha2Code: "EG",
		// numeric: 818,
	},
	{
		englishShortName: "El Salvador",
		frenchShortName: "El Salvador",
		alpha2Code: "SV",
		// numeric: 222,
	},
	{
		englishShortName: "Equatorial Guinea",
		frenchShortName: "Guinée équatoriale (la)",
		alpha2Code: "GQ",
		// numeric: 226,
	},
	{
		englishShortName: "Eritrea",
		frenchShortName: "Érythrée (l')",
		alpha2Code: "ER",
		// numeric: 232,
	},
	{
		englishShortName: "Estonia",
		frenchShortName: "Estonie (l')",
		alpha2Code: "EE",
		// numeric: 233,
	},
	{
		englishShortName: "Eswatini",
		frenchShortName: "Eswatini (l')",
		alpha2Code: "SZ",
		// numeric: 748,
	},
	{
		englishShortName: "Ethiopia",
		frenchShortName: "Éthiopie (l')",
		alpha2Code: "ET",
		// numeric: 231,
	},
	{
		englishShortName: "Falkland Islands (the) [Malvinas]",
		frenchShortName: "Falkland (les Îles)/Malouines (les Îles)",
		alpha2Code: "FK",
		// numeric: 238,
	},
	{
		englishShortName: "Faroe Islands (the)",
		frenchShortName: "Féroé (les Îles)",
		alpha2Code: "FO",
		// numeric: 234,
	},
	{
		englishShortName: "Fiji",
		frenchShortName: "Fidji (les)",
		alpha2Code: "FJ",
		// numeric: 242,
	},
	{
		englishShortName: "Finland",
		frenchShortName: "Finlande (la)",
		alpha2Code: "FI",
		// numeric: 246,
	},
	{
		englishShortName: "France",
		frenchShortName: "France (la)",
		alpha2Code: "FR",
		// numeric: 250,
	},
	{
		englishShortName: "French Guiana",
		frenchShortName: "Guyane française (la )",
		alpha2Code: "GF",
		// numeric: 254,
	},
	{
		englishShortName: "French Polynesia",
		frenchShortName: "Polynésie française (la)",
		alpha2Code: "PF",
		// numeric: 258,
	},
	{
		englishShortName: "French Southern Territories (the)",
		frenchShortName: "Terres australes françaises (les)",
		alpha2Code: "TF",
		// numeric: 260,
	},
	{
		englishShortName: "Gabon",
		frenchShortName: "Gabon (le)",
		alpha2Code: "GA",
		// numeric: 266,
	},
	{
		englishShortName: "Gambia (the)",
		frenchShortName: "Gambie (la)",
		alpha2Code: "GM",
		// numeric: 270,
	},
	{
		englishShortName: "Georgia",
		frenchShortName: "Géorgie (la)",
		alpha2Code: "GE",
		// numeric: 268,
	},
	{
		englishShortName: "Germany",
		frenchShortName: "Allemagne (l')",
		alpha2Code: "DE",
		// numeric: 276,
	},
	{
		englishShortName: "Ghana",
		frenchShortName: "Ghana (le)",
		alpha2Code: "GH",
		// numeric: 288,
	},
	{
		englishShortName: "Gibraltar",
		frenchShortName: "Gibraltar",
		alpha2Code: "GI",
		// numeric: 292,
	},
	{
		englishShortName: "Greece",
		frenchShortName: "Grèce (la)",
		alpha2Code: "GR",
		// numeric: 300,
	},
	{
		englishShortName: "Greenland",
		frenchShortName: "Groenland (le)",
		alpha2Code: "GL",
		// numeric: 304,
	},
	{
		englishShortName: "Grenada",
		frenchShortName: "Grenade (la)",
		alpha2Code: "GD",
		// numeric: 308,
	},
	{
		englishShortName: "Guadeloupe",
		frenchShortName: "Guadeloupe (la)",
		alpha2Code: "GP",
		// numeric: 312,
	},
	{
		englishShortName: "Guam",
		frenchShortName: "Guam",
		alpha2Code: "GU",
		// numeric: 316,
	},
	{
		englishShortName: "Guatemala",
		frenchShortName: "Guatemala (le)",
		alpha2Code: "GT",
		// numeric: 320,
	},
	{
		englishShortName: "Guernsey",
		frenchShortName: "Guernesey",
		alpha2Code: "GG",
		// numeric: 831,
	},
	{
		englishShortName: "Guinea",
		frenchShortName: "Guinée (la)",
		alpha2Code: "GN",
		// numeric: 324,
	},
	{
		englishShortName: "Guinea-Bissau",
		frenchShortName: "Guinée-Bissau (la)",
		alpha2Code: "GW",
		// numeric: 624,
	},
	{
		englishShortName: "Guyana",
		frenchShortName: "Guyana (le)",
		alpha2Code: "GY",
		// numeric: 328,
	},
	{
		englishShortName: "Haiti",
		frenchShortName: "Haïti",
		alpha2Code: "HT",
		// numeric: 332,
	},
	{
		englishShortName: "Heard Island and McDonald Islands",
		frenchShortName: "Heard-et-Îles MacDonald (l'Île)",
		alpha2Code: "HM",
		// numeric: 334,
	},
	{
		englishShortName: "Holy See (the)",
		frenchShortName: "Saint-Siège (le)",
		alpha2Code: "VA",
		// numeric: 336,
	},
	{
		englishShortName: "Honduras",
		frenchShortName: "Honduras (le)",
		alpha2Code: "HN",
		// numeric: 340,
	},
	{
		englishShortName: "Hong Kong",
		frenchShortName: "Hong Kong",
		alpha2Code: "HK",
		// numeric: 344,
	},
	{
		englishShortName: "Hungary",
		frenchShortName: "Hongrie (la)",
		alpha2Code: "HU",
		// numeric: 348,
	},
	{
		englishShortName: "Iceland",
		frenchShortName: "Islande (l')",
		alpha2Code: "IS",
		// numeric: 352,
	},
	{
		englishShortName: "India",
		frenchShortName: "Inde (l')",
		alpha2Code: "IN",
		// numeric: 356,
	},
	{
		englishShortName: "Indonesia",
		frenchShortName: "Indonésie (l')",
		alpha2Code: "ID",
		// numeric: 360,
	},
	{
		englishShortName: "Iran (Islamic Republic of)",
		frenchShortName: "Iran (République Islamique d')",
		alpha2Code: "IR",
		// numeric: 364,
	},
	{
		englishShortName: "Iraq",
		frenchShortName: "Iraq (l')",
		alpha2Code: "IQ",
		// numeric: 368,
	},
	{
		englishShortName: "Ireland",
		frenchShortName: "Irlande (l')",
		alpha2Code: "IE",
		// numeric: 372,
	},
	{
		englishShortName: "Isle of Man",
		frenchShortName: "Île de Man",
		alpha2Code: "IM",
		// numeric: 833,
	},
	{
		englishShortName: "Israel",
		frenchShortName: "Israël",
		alpha2Code: "IL",
		// numeric: 376,
	},
	{
		englishShortName: "Italy",
		frenchShortName: "Italie (l')",
		alpha2Code: "IT",
		// numeric: 380,
	},
	{
		englishShortName: "Jamaica",
		frenchShortName: "Jamaïque (la)",
		alpha2Code: "JM",
		// numeric: 388,
	},
	{
		englishShortName: "Japan",
		frenchShortName: "Japon (le)",
		alpha2Code: "JP",
		// numeric: 392,
	},
	{
		englishShortName: "Jersey",
		frenchShortName: "Jersey",
		alpha2Code: "JE",
		// numeric: 832,
	},
	{
		englishShortName: "Jordan",
		frenchShortName: "Jordanie (la)",
		alpha2Code: "JO",
		// numeric: 400,
	},
	{
		englishShortName: "Kazakhstan",
		frenchShortName: "Kazakhstan (le)",
		alpha2Code: "KZ",
		// numeric: 398,
	},
	{
		englishShortName: "Kenya",
		frenchShortName: "Kenya (le)",
		alpha2Code: "KE",
		// numeric: 404,
	},
	{
		englishShortName: "Kiribati",
		frenchShortName: "Kiribati",
		alpha2Code: "KI",
		// numeric: 296,
	},
	{
		englishShortName: "Korea (the Democratic People's Republic of)",
		frenchShortName: "Corée (la République populaire démocratique de)",
		alpha2Code: "KP",
		// numeric: 408,
	},
	{
		englishShortName: "Korea (the Republic of)",
		frenchShortName: "Corée (la République de)",
		alpha2Code: "KR",
		// numeric: 410,
	},
	{
		englishShortName: "Kuwait",
		frenchShortName: "Koweït (le)",
		alpha2Code: "KW",
		// numeric: 414,
	},
	{
		englishShortName: "Kyrgyzstan",
		frenchShortName: "Kirghizistan (le)",
		alpha2Code: "KG",
		// numeric: 417,
	},
	{
		englishShortName: "Lao People's Democratic Republic (the)",
		frenchShortName: "Lao (la République démocratique populaire)",
		alpha2Code: "LA",
		// numeric: 418,
	},
	{
		englishShortName: "Latvia",
		frenchShortName: "Lettonie (la)",
		alpha2Code: "LV",
		// numeric: 428,
	},
	{
		englishShortName: "Lebanon",
		frenchShortName: "Liban (le)",
		alpha2Code: "LB",
		// numeric: 422,
	},
	{
		englishShortName: "Lesotho",
		frenchShortName: "Lesotho (le)",
		alpha2Code: "LS",
		// numeric: 426,
	},
	{
		englishShortName: "Liberia",
		frenchShortName: "Libéria (le)",
		alpha2Code: "LR",
		// numeric: 430,
	},
	{
		englishShortName: "Libya",
		frenchShortName: "Libye (la)",
		alpha2Code: "LY",
		// numeric: 434,
	},
	{
		englishShortName: "Liechtenstein",
		frenchShortName: "Liechtenstein (le)",
		alpha2Code: "LI",
		// numeric: 438,
	},
	{
		englishShortName: "Lithuania",
		frenchShortName: "Lituanie (la)",
		alpha2Code: "LT",
		// numeric: 440,
	},
	{
		englishShortName: "Luxembourg",
		frenchShortName: "Luxembourg (le)",
		alpha2Code: "LU",
		// numeric: 442,
	},
	{
		englishShortName: "Macao",
		frenchShortName: "Macao",
		alpha2Code: "MO",
		// numeric: 446,
	},
	{
		englishShortName: "Madagascar",
		frenchShortName: "Madagascar",
		alpha2Code: "MG",
		// numeric: 450,
	},
	{
		englishShortName: "Malawi",
		frenchShortName: "Malawi (le)",
		alpha2Code: "MW",
		// numeric: 454,
	},
	{
		englishShortName: "Malaysia",
		frenchShortName: "Malaisie (la)",
		alpha2Code: "MY",
		// numeric: 458,
	},
	{
		englishShortName: "Maldives",
		frenchShortName: "Maldives (les)",
		alpha2Code: "MV",
		// numeric: 462,
	},
	{
		englishShortName: "Mali",
		frenchShortName: "Mali (le)",
		alpha2Code: "ML",
		// numeric: 466,
	},
	{
		englishShortName: "Malta",
		frenchShortName: "Malte",
		alpha2Code: "MT",
		// numeric: 470,
	},
	{
		englishShortName: "Marshall Islands (the)",
		frenchShortName: "Marshall (les Îles)",
		alpha2Code: "MH",
		// numeric: 584,
	},
	{
		englishShortName: "Martinique",
		frenchShortName: "Martinique (la)",
		alpha2Code: "MQ",
		// numeric: 474,
	},
	{
		englishShortName: "Mauritania",
		frenchShortName: "Mauritanie (la)",
		alpha2Code: "MR",
		// numeric: 478,
	},
	{
		englishShortName: "Mauritius",
		frenchShortName: "Maurice",
		alpha2Code: "MU",
		// numeric: 480,
	},
	{
		englishShortName: "Mayotte",
		frenchShortName: "Mayotte",
		alpha2Code: "YT",
		// numeric: 175,
	},
	{
		englishShortName: "Mexico",
		frenchShortName: "Mexique (le)",
		alpha2Code: "MX",
		// numeric: 484,
	},
	{
		englishShortName: "Micronesia (Federated States of)",
		frenchShortName: "Micronésie (États fédérés de)",
		alpha2Code: "FM",
		// numeric: 583,
	},
	{
		englishShortName: "Moldova (the Republic of)",
		frenchShortName: "Moldova (la République de)",
		alpha2Code: "MD",
		// numeric: 498,
	},
	{
		englishShortName: "Monaco",
		frenchShortName: "Monaco",
		alpha2Code: "MC",
		// numeric: 492,
	},
	{
		englishShortName: "Mongolia",
		frenchShortName: "Mongolie (la)",
		alpha2Code: "MN",
		// numeric: 496,
	},
	{
		englishShortName: "Montenegro",
		frenchShortName: "Monténégro (le)",
		alpha2Code: "ME",
		// numeric: 499,
	},
	{
		englishShortName: "Montserrat",
		frenchShortName: "Montserrat",
		alpha2Code: "MS",
		// numeric: 500,
	},
	{
		englishShortName: "Morocco",
		frenchShortName: "Maroc (le)",
		alpha2Code: "MA",
		// numeric: 504,
	},
	{
		englishShortName: "Mozambique",
		frenchShortName: "Mozambique (le)",
		alpha2Code: "MZ",
		// numeric: 508,
	},
	{
		englishShortName: "Myanmar",
		frenchShortName: "Myanmar (le)",
		alpha2Code: "MM",
		// numeric: 104,
	},
	{
		englishShortName: "Namibia",
		frenchShortName: "Namibie (la)",
		alpha2Code: "NA",
		// numeric: 516,
	},
	{
		englishShortName: "Nauru",
		frenchShortName: "Nauru",
		alpha2Code: "NR",
		// numeric: 520,
	},
	{
		englishShortName: "Nepal",
		frenchShortName: "Népal (le)",
		alpha2Code: "NP",
		// numeric: 524,
	},
	{
		englishShortName: "Netherlands (the)",
		frenchShortName: "Pays-Bas (les)",
		alpha2Code: "NL",
		// numeric: 528,
	},
	{
		englishShortName: "New Caledonia",
		frenchShortName: "Nouvelle-Calédonie (la)",
		alpha2Code: "NC",
		// numeric: 540,
	},
	{
		englishShortName: "New Zealand",
		frenchShortName: "Nouvelle-Zélande (la)",
		alpha2Code: "NZ",
		// numeric: 554,
	},
	{
		englishShortName: "Nicaragua",
		frenchShortName: "Nicaragua (le)",
		alpha2Code: "NI",
		// numeric: 558,
	},
	{
		englishShortName: "Niger (the)",
		frenchShortName: "Niger (le)",
		alpha2Code: "NE",
		// numeric: 562,
	},
	{
		englishShortName: "Nigeria",
		frenchShortName: "Nigéria (le)",
		alpha2Code: "NG",
		// numeric: 566,
	},
	{
		englishShortName: "Niue",
		frenchShortName: "Niue",
		alpha2Code: "NU",
		// numeric: 570,
	},
	{
		englishShortName: "Norfolk Island",
		frenchShortName: "Norfolk (l'Île)",
		alpha2Code: "NF",
		// numeric: 574,
	},
	{
		englishShortName: "North Macedonia",
		frenchShortName: "Macédoine du Nord (la)",
		alpha2Code: "MK",
		// numeric: 807,
	},
	{
		englishShortName: "Northern Mariana Islands (the)",
		frenchShortName: "Mariannes du Nord (les Îles)",
		alpha2Code: "MP",
		// numeric: 580,
	},
	{
		englishShortName: "Norway",
		frenchShortName: "Norvège (la)",
		alpha2Code: "NO",
		// numeric: 578,
	},
	{
		englishShortName: "Oman",
		frenchShortName: "Oman",
		alpha2Code: "OM",
		// numeric: 512,
	},
	{
		englishShortName: "Pakistan",
		frenchShortName: "Pakistan (le)",
		alpha2Code: "PK",
		// numeric: 586,
	},
	{
		englishShortName: "Palau",
		frenchShortName: "Palaos (les)",
		alpha2Code: "PW",
		// numeric: 585,
	},
	{
		englishShortName: "Palestine, State of",
		frenchShortName: "Palestine, État de",
		alpha2Code: "PS",
		// numeric: 275,
	},
	{
		englishShortName: "Panama",
		frenchShortName: "Panama (le)",
		alpha2Code: "PA",
		// numeric: 591,
	},
	{
		englishShortName: "Papua New Guinea",
		frenchShortName: "Papouasie-Nouvelle-Guinée (la)",
		alpha2Code: "PG",
		// numeric: 598,
	},
	{
		englishShortName: "Paraguay",
		frenchShortName: "Paraguay (le)",
		alpha2Code: "PY",
		// numeric: 600,
	},
	{
		englishShortName: "Peru",
		frenchShortName: "Pérou (le)",
		alpha2Code: "PE",
		// numeric: 604,
	},
	{
		englishShortName: "Philippines (the)",
		frenchShortName: "Philippines (les)",
		alpha2Code: "PH",
		// numeric: 608,
	},
	{
		englishShortName: "Pitcairn",
		frenchShortName: "Pitcairn",
		alpha2Code: "PN",
		// numeric: 612,
	},
	{
		englishShortName: "Poland",
		frenchShortName: "Pologne (la)",
		alpha2Code: "PL",
		// numeric: 616,
	},
	{
		englishShortName: "Portugal",
		frenchShortName: "Portugal (le)",
		alpha2Code: "PT",
		// numeric: 620,
	},
	{
		englishShortName: "Puerto Rico",
		frenchShortName: "Porto Rico",
		alpha2Code: "PR",
		// numeric: 630,
	},
	{
		englishShortName: "Qatar",
		frenchShortName: "Qatar (le)",
		alpha2Code: "QA",
		// numeric: 634,
	},
	{
		englishShortName: "Romania",
		frenchShortName: "Roumanie (la)",
		alpha2Code: "RO",
		// numeric: 642,
	},
	{
		englishShortName: "Russian Federation (the)",
		frenchShortName: "Russie (la Fédération de)",
		alpha2Code: "RU",
		// numeric: 643,
	},
	{
		englishShortName: "Rwanda",
		frenchShortName: "Rwanda (le)",
		alpha2Code: "RW",
		// numeric: 646,
	},
	{
		englishShortName: "Réunion",
		frenchShortName: "Réunion (La)",
		alpha2Code: "RE",
		// numeric: 638,
	},
	{
		englishShortName: "Saint Barthélemy",
		frenchShortName: "Saint-Barthélemy",
		alpha2Code: "BL",
		// numeric: 652,
	},
	{
		englishShortName: "Saint Helena, Ascension and Tristan da Cunha",
		frenchShortName: "Sainte-Hélène, Ascension et Tristan da Cunha",
		alpha2Code: "SH",
		// numeric: 654,
	},
	{
		englishShortName: "Saint Kitts and Nevis",
		frenchShortName: "Saint-Kitts-et-Nevis",
		alpha2Code: "KN",
		// numeric: 659,
	},
	{
		englishShortName: "Saint Lucia",
		frenchShortName: "Sainte-Lucie",
		alpha2Code: "LC",
		// numeric: 662,
	},
	{
		englishShortName: "Saint Martin (French part)",
		frenchShortName: "Saint-Martin (partie française)",
		alpha2Code: "MF",
		// numeric: 663,
	},
	{
		englishShortName: "Saint Pierre and Miquelon",
		frenchShortName: "Saint-Pierre-et-Miquelon",
		alpha2Code: "PM",
		// numeric: 666,
	},
	{
		englishShortName: "Saint Vincent and the Grenadines",
		frenchShortName: "Saint-Vincent-et-les Grenadines",
		alpha2Code: "VC",
		// numeric: 670,
	},
	{
		englishShortName: "Samoa",
		frenchShortName: "Samoa (le)",
		alpha2Code: "WS",
		// numeric: 882,
	},
	{
		englishShortName: "San Marino",
		frenchShortName: "Saint-Marin",
		alpha2Code: "SM",
		// numeric: 674,
	},
	{
		englishShortName: "Sao Tome and Principe",
		frenchShortName: "Sao Tomé-et-Principe",
		alpha2Code: "ST",
		// numeric: 678,
	},
	{
		englishShortName: "Saudi Arabia",
		frenchShortName: "Arabie saoudite (l')",
		alpha2Code: "SA",
		// numeric: 682,
	},
	{
		englishShortName: "Senegal",
		frenchShortName: "Sénégal (le)",
		alpha2Code: "SN",
		// numeric: 686,
	},
	{
		englishShortName: "Serbia",
		frenchShortName: "Serbie (la)",
		alpha2Code: "RS",
		// numeric: 688,
	},
	{
		englishShortName: "Seychelles",
		frenchShortName: "Seychelles (les)",
		alpha2Code: "SC",
		// numeric: 690,
	},
	{
		englishShortName: "Sierra Leone",
		frenchShortName: "Sierra Leone (la)",
		alpha2Code: "SL",
		// numeric: 694,
	},
	{
		englishShortName: "Singapore",
		frenchShortName: "Singapour",
		alpha2Code: "SG",
		// numeric: 702,
	},
	{
		englishShortName: "Sint Maarten (Dutch part)",
		frenchShortName: "Saint-Martin (partie néerlandaise)",
		alpha2Code: "SX",
		// numeric: 534,
	},
	{
		englishShortName: "Slovakia",
		frenchShortName: "Slovaquie (la)",
		alpha2Code: "SK",
		// numeric: 703,
	},
	{
		englishShortName: "Slovenia",
		frenchShortName: "Slovénie (la)",
		alpha2Code: "SI",
		// numeric: 705,
	},
	{
		englishShortName: "Solomon Islands",
		frenchShortName: "Salomon (les Îles)",
		alpha2Code: "SB",
		// numeric: 90,
	},
	{
		englishShortName: "Somalia",
		frenchShortName: "Somalie (la)",
		alpha2Code: "SO",
		// numeric: 706,
	},
	{
		englishShortName: "South Africa",
		frenchShortName: "Afrique du Sud (l')",
		alpha2Code: "ZA",
		// numeric: 710,
	},
	{
		englishShortName: "South Georgia and the South Sandwich Islands",
		frenchShortName: "Géorgie du Sud-et-les Îles Sandwich du Sud (la)",
		alpha2Code: "GS",
		// numeric: 239,
	},
	{
		englishShortName: "South Sudan",
		frenchShortName: "Soudan du Sud (le)",
		alpha2Code: "SS",
		// numeric: 728,
	},
	{
		englishShortName: "Spain",
		frenchShortName: "Espagne (l')",
		alpha2Code: "ES",
		// numeric: 724,
	},
	{
		englishShortName: "Sri Lanka",
		frenchShortName: "Sri Lanka",
		alpha2Code: "LK",
		// numeric: 144,
	},
	{
		englishShortName: "Sudan (the)",
		frenchShortName: "Soudan (le)",
		alpha2Code: "SD",
		// numeric: 729,
	},
	{
		englishShortName: "Suriname",
		frenchShortName: "Suriname (le)",
		alpha2Code: "SR",
		// numeric: 740,
	},
	{
		englishShortName: "Svalbard and Jan Mayen",
		frenchShortName: "Svalbard et l'Île Jan Mayen (le)",
		alpha2Code: "SJ",
		// numeric: 744,
	},
	{
		englishShortName: "Sweden",
		frenchShortName: "Suède (la)",
		alpha2Code: "SE",
		// numeric: 752,
	},
	{
		englishShortName: "Switzerland",
		frenchShortName: "Suisse (la)",
		alpha2Code: "CH",
		// numeric: 756,
	},
	{
		englishShortName: "Syrian Arab Republic (the)",
		frenchShortName: "République arabe syrienne (la)",
		alpha2Code: "SY",
		// numeric: 760,
	},
	{
		englishShortName: "Taiwan (Province of China)",
		frenchShortName: "Taïwan (Province de Chine)",
		alpha2Code: "TW",
		// numeric: 158,
	},
	{
		englishShortName: "Tajikistan",
		frenchShortName: "Tadjikistan (le)",
		alpha2Code: "TJ",
		// numeric: 762,
	},
	{
		englishShortName: "Tanzania, the United Republic of",
		frenchShortName: "Tanzanie (la République-Unie de)",
		alpha2Code: "TZ",
		// numeric: 834,
	},
	{
		englishShortName: "Thailand",
		frenchShortName: "Thaïlande (la)",
		alpha2Code: "TH",
		// numeric: 764,
	},
	{
		englishShortName: "Timor-Leste",
		frenchShortName: "Timor-Leste (le)",
		alpha2Code: "TL",
		// numeric: 626,
	},
	{
		englishShortName: "Togo",
		frenchShortName: "Togo (le)",
		alpha2Code: "TG",
		// numeric: 768,
	},
	{
		englishShortName: "Tokelau",
		frenchShortName: "Tokelau (les)",
		alpha2Code: "TK",
		// numeric: 772,
	},
	{
		englishShortName: "Tonga",
		frenchShortName: "Tonga (les)",
		alpha2Code: "TO",
		// numeric: 776,
	},
	{
		englishShortName: "Trinidad and Tobago",
		frenchShortName: "Trinité-et-Tobago (la)",
		alpha2Code: "TT",
		// numeric: 780,
	},
	{
		englishShortName: "Tunisia",
		frenchShortName: "Tunisie (la)",
		alpha2Code: "TN",
		// numeric: 788,
	},
	{
		englishShortName: "Turkey",
		frenchShortName: "Turquie (la)",
		alpha2Code: "TR",
		// numeric: 792,
	},
	{
		englishShortName: "Turkmenistan",
		frenchShortName: "Turkménistan (le)",
		alpha2Code: "TM",
		// numeric: 795,
	},
	{
		englishShortName: "Turks and Caicos Islands (the)",
		frenchShortName: "Turks-et-Caïcos (les Îles)",
		alpha2Code: "TC",
		// numeric: 796,
	},
	{
		englishShortName: "Tuvalu",
		frenchShortName: "Tuvalu (les)",
		alpha2Code: "TV",
		// numeric: 798,
	},
	{
		englishShortName: "Uganda",
		frenchShortName: "Ouganda (l')",
		alpha2Code: "UG",
		// numeric: 800,
	},
	{
		englishShortName: "Ukraine",
		frenchShortName: "Ukraine (l')",
		alpha2Code: "UA",
		// numeric: 804,
	},
	{
		englishShortName: "United Arab Emirates (the)",
		frenchShortName: "Émirats arabes unis (les)",
		alpha2Code: "AE",
		// numeric: 784,
	},
	{
		englishShortName:
			"United Kingdom of Great Britain and Northern Ireland (the)",
		frenchShortName:
			"Royaume-Uni de Grande-Bretagne et d'Irlande du Nord (le)",
		alpha2Code: "GB",
		// numeric: 826,
	},
	{
		englishShortName: "United States Minor Outlying Islands (the)",
		frenchShortName: "Îles mineures éloignées des États-Unis (les)",
		alpha2Code: "UM",
		// numeric: 581,
	},
	{
		englishShortName: "United States of America (the)",
		frenchShortName: "États-Unis d'Amérique (les)",
		alpha2Code: "US",
		// numeric: 840,
	},
	{
		englishShortName: "Uruguay",
		frenchShortName: "Uruguay (l')",
		alpha2Code: "UY",
		// numeric: 858,
	},
	{
		englishShortName: "Uzbekistan",
		frenchShortName: "Ouzbékistan (l')",
		alpha2Code: "UZ",
		// numeric: 860,
	},
	{
		englishShortName: "Vanuatu",
		frenchShortName: "Vanuatu (le)",
		alpha2Code: "VU",
		// numeric: 548,
	},
	{
		englishShortName: "Venezuela (Bolivarian Republic of)",
		frenchShortName: "Venezuela (République bolivarienne du)",
		alpha2Code: "VE",
		// numeric: 862,
	},
	{
		englishShortName: "Viet Nam",
		frenchShortName: "Viet Nam (le)",
		alpha2Code: "VN",
		// numeric: 704,
	},
	{
		englishShortName: "Virgin Islands (British)",
		frenchShortName: "Vierges britanniques (les Îles)",
		alpha2Code: "VG",
		// numeric: 92,
	},
	{
		englishShortName: "Virgin Islands (U.S.)",
		frenchShortName: "Vierges des États-Unis (les Îles)",
		alpha2Code: "VI",
		// numeric: 850,
	},
	{
		englishShortName: "Wallis and Futuna",
		frenchShortName: "Wallis-et-Futuna",
		alpha2Code: "WF",
		// numeric: 876,
	},
	{
		englishShortName: "Western Sahara*",
		frenchShortName: "Sahara occidental (le)*",
		alpha2Code: "EH",
		// numeric: 732,
	},
	{
		englishShortName: "Yemen",
		frenchShortName: "Yémen (le)",
		alpha2Code: "YE",
		// numeric: 887,
	},
	{
		englishShortName: "Zambia",
		frenchShortName: "Zambie (la)",
		alpha2Code: "ZM",
		// numeric: 894,
	},
	{
		englishShortName: "Zimbabwe",
		frenchShortName: "Zimbabwe (le)",
		alpha2Code: "ZW",
		// numeric: 716,
	},
	{
		englishShortName: "Åland Islands",
		frenchShortName: "Åland(les Îles)",
		alpha2Code: "AX",
		// numeric: 248,
	},
];
